// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitpxUC6uoF5-_c-LuqiggG6y3nJG4Sts',
    appId: '1:1077230982743:web:34ab16cd146a3178eb3512',
    messagingSenderId: '1077230982743',
    projectId: 'handsinwordssystem',
    authDomain: 'handsinwordssystem.firebaseapp.com',
    storageBucket: 'handsinwordssystem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaSEcJzdRjRU71Mi8e2_ikVv-EFQQIL3o',
    appId: '1:1077230982743:android:a595b38c3f9ffd9ceb3512',
    messagingSenderId: '1077230982743',
    projectId: 'handsinwordssystem',
    storageBucket: 'handsinwordssystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ00IAYNfT_-CzXU9-2iyYCl54ePPb3BI',
    appId: '1:1077230982743:ios:42c08d37fe6bc3c2eb3512',
    messagingSenderId: '1077230982743',
    projectId: 'handsinwordssystem',
    storageBucket: 'handsinwordssystem.firebasestorage.app',
    iosBundleId: 'com.example.secondApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ00IAYNfT_-CzXU9-2iyYCl54ePPb3BI',
    appId: '1:1077230982743:ios:42c08d37fe6bc3c2eb3512',
    messagingSenderId: '1077230982743',
    projectId: 'handsinwordssystem',
    storageBucket: 'handsinwordssystem.firebasestorage.app',
    iosBundleId: 'com.example.secondApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAitpxUC6uoF5-_c-LuqiggG6y3nJG4Sts',
    appId: '1:1077230982743:web:c604c0d2869e9e03eb3512',
    messagingSenderId: '1077230982743',
    projectId: 'handsinwordssystem',
    authDomain: 'handsinwordssystem.firebaseapp.com',
    storageBucket: 'handsinwordssystem.firebasestorage.app',
  );
}
